name: Refresh kernel 6.12 + experimental
on:
   workflow_dispatch:
jobs:
    build:
        name: kernel + experimental
        runs-on: ubuntu-24.04-arm
        steps:
             - name: checkout
               uses: actions/checkout@v4
             - name: refresh kernel              
               run: |
                git clone https://github.com/openwrt/openwrt.git
                git config --global user.email l@ton.me
                git config --global user.name 'J R'
                cp -rf .github/workflows/pm.patch openwrt/
                cd openwrt
                git am pm.patch
                sed -i 's/38/39/g' target/linux/generic/kernel-6.12
                sed -i 's/f035fa8d83d59f793c76b23567b130cc42118f10696815fed03c16bb15670fcc/dd14a5257b13e521b40ba7225099dea272df5d1cb419945e17c38f870fdc55f4/g' target/linux/generic/kernel-6.12
                rm -f .config
                rm -rf tmp
                echo "CONFIG_TARGET_airoha=y" >> .config
                echo "CONFIG_TARGET_airoha_en7523=y" >> .config
                echo "CONFIG_ALL_KMODS=y" >> .config
                echo "CONFIG_EXPERIMENTAL=y" >> .config
                echo "CONFIG_BUILD_LOG=y" >> .config
                make defconfig
                make tools/quilt/compile -j$(nproc)
                make target/linux/{clean,refresh} -j$(nproc) V=s

                git clean -d -f .
                git add .
                git commit -s -m "kernel 6.12"
                git format-patch -1
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
             - name: Delete tag
               uses: ClementTsang/delete-tag-and-release@v0.4.0
               with:
                delete_release: true
                tag_name: kernel-6.12-exp
               env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             - name: Create release
               uses: ncipollo/release-action@v1.14.0
               with:
                allowUpdates: true
                name: Kernel 6.12+exp ${{ env.D }}
                tag: kernel-6.12-exp
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: |
                          openwrt/0001-kernel-6.12.patch
                          openwrt/logs.tar.gz
